/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package detail.network;

/**
 *
 * @author Eudy
 */
public class View1 extends javax.swing.JFrame {
    
    private int octeto[] ={1,2,4,8,16,32,64,128};
    private char addressClass=' ';
    private String defaultMask[] = {"255","0","0","0"};
    private int zero=0,totalOcteto=0,countSubnet=1,countHosts=1,countBits=1,bistsBorrowed=0,totalOposit=1,customMask=0;
    private Boolean hostORSubnet = true;
    /**
     * Creates new form Vista1
     */
    public View1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Add your address network");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("How many usable host");

        jLabel3.setText("How many usable network");

        jButton1.setText("calculate");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.calculateDetail();
    }//GEN-LAST:event_jButton1MouseClicked
    
    public void calculateDetail(){
        //Clear all variable
        this.clearAll();
        //identify class of address
        this.identifyClassAddress();
        //zeros of address
        this.totalZero();
        //calculate total of octetos
        this.calculateOctetosAble();
        //calculate total of hosts
        this.identifySubnetsOrHosts();
        //Search bits barrowod of subnet
        this.getBistsBorrowed();
        //calculate oposit (if is it hosts the oposit is subnet and if is it subnet the oposit is hosts)
        this.calculateOposit();
        //print all information
        this.printAll();
    }
    public void identifySubnetsOrHosts(){
        if(!(this.jTextField6.getText().isEmpty())){
           this.calculateSubnet();
        }else if(!(this.jTextField5.getText().isEmpty())){
            this.calculateHosts();
        }else{
           this.showMessange("Can not calculate, need to add number of subnets or number of hosts");
        }
    }
    public void showMessange(String arg){
        System.out.println(arg);
    }
    public void calculateSubnet(){
         this.hostORSubnet = false;
         int needSubnet = Integer.parseInt(this.jTextField6.getText());
        System.out.println("Total Subnet "+needSubnet);
        this.countSubnet = 2;
        while(needSubnet > (this.countSubnet - 2)){
            this.countSubnet = this.countSubnet * 2;
            this.countBits = this.countBits + 1;
        }
        System.out.println("Bits: "+this.countBits);
    }
    public void calculateOctetosAble(){
        this.totalOcteto = this.zero * 8;
    }
    public void calculateHosts(){
        this.hostORSubnet = true;
        int needHosts = Integer.parseInt(this.jTextField5.getText());
        System.out.println("Total Hosts "+needHosts);
        this.countHosts = 2;
        while(needHosts > (this.countHosts - 2)){
            this.countHosts = this.countHosts * 2;
            this.countBits = this.countBits + 1;
        }
        System.out.println("Bits: "+this.countBits);
    }
    public void calculateOposit(){
        int numero = 7;
        for(int i = this.bistsBorrowed ; i > 0 ; i--){
            this.totalOposit= this.totalOposit * 2;
            this.customMask = this.customMask + this.octeto[numero];
            numero--;
        }
    }
    public void clearAll(){
        this.zero = 0;
        this.addressClass = ' ';
        this.defaultMask[1] = "0";this.defaultMask[2] = "0";this.defaultMask[3] = "0";
        this.countHosts = 1;this.countSubnet = 1;
    }
    public void getBistsBorrowed(){
        System.out.println("Octetos: "+this.totalOcteto);
        this.bistsBorrowed = this.totalOcteto - this.countBits;
        if(this.bistsBorrowed < 0){
            this.bistsBorrowed = this.bistsBorrowed * -1;
        }
    }
    
    public void printAll(){
       System.out.println("Total of zero :"+this.zero);
       System.out.println("Class of network :"+this.addressClass);
       System.out.println("Default mask :"+String.join(".",this.defaultMask));
       System.out.println("Total number of hosts :"+this.countHosts);
       System.out.println("Bists Borrowed :"+this.bistsBorrowed);
       System.out.println("Total number of subnet :"+this.totalOposit);

    }
    public void totalZero(){
        int firstOctecto = Integer.parseInt(this.jTextField1.getText());
        int secondOctecto = Integer.parseInt(this.jTextField2.getText());
        int thirdOctecto = Integer.parseInt(this.jTextField3.getText());
        int fourthOctecto = Integer.parseInt(this.jTextField4.getText());
        
            if(firstOctecto == 0){
                this.zero = this.zero+1;
            }
            if(secondOctecto == 0){
                this.zero = this.zero+1;
            }
            if(thirdOctecto == 0){
                this.zero = this.zero+1;
            }
            if(fourthOctecto == 0){
                this.zero = this.zero+1;
            }
        
        

    }
    public void identifyClassAddress(){
       int firstOctecto = Integer.parseInt(this.jTextField1.getText());
       if(firstOctecto >= 1 && firstOctecto <= 127){
           this.addressClass = 'A';
           
       }else if(firstOctecto >= 128 && firstOctecto <= 191){
           this.addressClass = 'B';
           this.defaultMask[1]="255";
       }else if(firstOctecto >= 192 && firstOctecto <= 223){
           this.addressClass = 'C';
           this.defaultMask[1]="255";this.defaultMask[2]="255";
           
       }else if(firstOctecto >= 224 && firstOctecto <= 239){
           this.addressClass = 'D';
       }else if(firstOctecto >= 240 && firstOctecto <= 255){
           this.addressClass = 'E';
       }
    }
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
